application: gae-xero
version: 1
runtime: python27
threadsafe: true
api_version: 1

libraries:
- name: pycrypto
  version: latest
- name: lxml  
  version: "2.3"
- name: webapp2
  version: latest
- name: jinja2
  version: latest
  
handlers:
- url: /.*
  script: xerointegration.application
